import {
  pgTable,
  text,
  integer,
  bigint,
  real,
  boolean,
  timestamp,
  date,
  index,
  unique,
} from 'drizzle-orm/pg-core'
import { createId } from '@paralleldrive/cuid2'

// `user`, `session`, `account` and `verification` are generated by the Better
// Auth CLI. Re-exported here because drizzle.config.ts points at this file
// alone, so anything not reachable from it is absent from the migration.
export * from './auth-schema'

// There is deliberately NO segments table (SPEC 1.3). The filesystem plus
// MediaMTX's /list is the source of truth for what was recorded; a second
// index drifts the first time a file is deleted out-of-band, and a timeline
// that disagrees with the disk is worse than no timeline.

export const cameras = pgTable('cameras', {
  id: text('id').primaryKey().$defaultFn(createId),
  slug: text('slug').notNull().unique(), // MediaMTX path name
  name: text('name').notNull(),
  rtspMain: text('rtsp_main').notNull(), // channel0 — recorded
  rtspSub: text('rtsp_sub'), // channel1 — live view
  enabled: boolean('enabled').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Transitions only — one row when the stream goes down, one when it comes back.
// Polling every 10s and writing every poll would be 8,640 rows/day of nothing.
export const streamEvents = pgTable(
  'stream_events',
  {
    id: text('id').primaryKey().$defaultFn(createId),
    cameraSlug: text('camera_slug')
      .notNull()
      .references(() => cameras.slug, { onDelete: 'cascade' }),
    kind: text('kind', { enum: ['up', 'down'] }).notNull(),
    at: timestamp('at', { withTimezone: true }).notNull(),
    detail: text('detail'),
  },
  (t) => [index('stream_events_slug_at_idx').on(t.cameraSlug, t.at)],
)

// Written nightly. Recordings are deleted after the retention window; the
// record of how reliable the system was should outlive them.
export const dailyCoverage = pgTable(
  'daily_coverage',
  {
    id: text('id').primaryKey().$defaultFn(createId),
    cameraSlug: text('camera_slug')
      .notNull()
      .references(() => cameras.slug, { onDelete: 'cascade' }),
    day: date('day').notNull(), // camera-local calendar day
    coverage: real('coverage').notNull(), // 0..1
    gapCount: integer('gap_count').notNull(),
    longestGapSec: integer('longest_gap_sec').notNull(),
    // 2.5 Mbps is ~27 GB/day. int4 tops out at 2.1e9 and would overflow on the
    // second day — this must be bigint.
    bytesWritten: bigint('bytes_written', { mode: 'number' }),
  },
  // The unique constraint is what makes the nightly snapshot idempotent: it
  // upserts on conflict, so re-running a day overwrites rather than
  // duplicating. The constraint enforces it, not the application remembering to.
  (t) => [unique('daily_coverage_slug_day_key').on(t.cameraSlug, t.day)],
)
